// Generated by production/pipeline/export_cameras.py from the Blender shots: every camera in
// glTF / three.js coordinates (Y up, metres), and each cup's outward axis. Do not edit by hand.
export interface ShotCamera {
  pos: number[]
  target: number[]
  up: number[]
  lens: number
  shift: number[]
  aspect: number
}
export const SHOT_CAMERAS: Record<string, ShotCamera> = {
  "hero_desk": {
    "pos": [
      0.52,
      0.2,
      0.74
    ],
    "target": [
      0.012,
      0.098,
      -0.0
    ],
    "up": [
      -0.0639,
      0.99361,
      -0.09309
    ],
    "lens": 50.0,
    "shift": [
      -0.12,
      0.0
    ],
    "aspect": 1.5
  },
  "hero_portrait": {
    "pos": [
      0.46,
      0.24,
      0.66
    ],
    "target": [
      0.01,
      0.1,
      -0.0
    ],
    "up": [
      -0.09725,
      0.98499,
      -0.14263
    ],
    "lens": 50.0,
    "shift": [
      0.0,
      0.13
    ],
    "aspect": 0.6
  },
  "ring_desktop": {
    "pos": [
      0.17438,
      0.04653,
      0.01255
    ],
    "target": [
      0.09823,
      0.08933,
      0.02559
    ],
    "up": [
      0.47761,
      0.87476,
      -0.08177
    ],
    "lens": 100.0,
    "shift": [
      0.0,
      0.0
    ],
    "aspect": 1.5
  },
  "ring_portrait": {
    "pos": [
      0.17624,
      0.05299,
      0.0169
    ],
    "target": [
      0.09823,
      0.08933,
      0.02559
    ],
    "up": [
      0.41759,
      0.90744,
      -0.04653
    ],
    "lens": 85.0,
    "shift": [
      0.0,
      0.0
    ],
    "aspect": 0.6
  },
  "final_desk": {
    "pos": [
      0.0,
      0.12,
      0.95
    ],
    "target": [
      0.0,
      0.1,
      -0.0
    ],
    "up": [
      0.0,
      0.99978,
      -0.02105
    ],
    "lens": 55.0,
    "shift": [
      0.0,
      -0.09
    ],
    "aspect": 1.5
  },
  "final_portrait": {
    "pos": [
      0.0,
      0.15,
      0.9
    ],
    "target": [
      0.0,
      0.11,
      -0.0
    ],
    "up": [
      0.0,
      0.99901,
      -0.0444
    ],
    "lens": 80.0,
    "shift": [
      0.0,
      -0.04
    ],
    "aspect": 0.6
  },
  "view_front": {
    "pos": [
      0.0,
      0.11,
      1.0
    ],
    "target": [
      0.0,
      0.106,
      -0.0
    ],
    "up": [
      0.0,
      0.99999,
      -0.004
    ],
    "lens": 105.0,
    "shift": [
      0.0,
      0.0
    ],
    "aspect": 1.0
  },
  "view_side": {
    "pos": [
      1.0,
      0.11,
      -0.0
    ],
    "target": [
      0.0,
      0.106,
      -0.0
    ],
    "up": [
      -0.004,
      0.99999,
      0.0
    ],
    "lens": 105.0,
    "shift": [
      0.0,
      0.0
    ],
    "aspect": 1.0
  },
  "view_back": {
    "pos": [
      0.0,
      0.11,
      -1.0
    ],
    "target": [
      0.0,
      0.106,
      -0.0
    ],
    "up": [
      -0.0,
      0.99999,
      0.004
    ],
    "lens": 105.0,
    "shift": [
      0.0,
      0.0
    ],
    "aspect": 1.0
  },
  "view_34": {
    "pos": [
      0.6,
      0.34,
      0.74
    ],
    "target": [
      0.0,
      0.106,
      -0.0
    ],
    "up": [
      -0.15023,
      0.97113,
      -0.18528
    ],
    "lens": 105.0,
    "shift": [
      0.0,
      0.0
    ],
    "aspect": 1.0
  }
}
export const CUP_AXES = {"R": [0.96126, -0.27564, 0.0], "L": [-0.96126, -0.27564, 0.0], "centreR": [0.08728, 0.05119, -0.0], "centreL": [-0.08728, 0.05119, -0.0]}
