"""The shots' cameras, for the web stage. Builds the hero, ring, final and view scenes exactly as
pulse_shots does — rendering nothing — and writes each camera (position, aim, up, lens, shift,
frame aspect) plus each cup's outward axis to src/projects/pulse/stage-cams.ts, converted from
Blender (Z up) to glTF / three.js (Y up). The live product then starts and ends exactly where
the renders are, so the page can cut between the two without a jump.

    blender -b MASTER --python production/pipeline/export_cameras.py
"""
import sys
import json
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import bpy  # noqa: E402
from mathutils import Vector  # noqa: E402
import pulse_lib as L  # noqa: E402
import pulse_shots as S  # noqa: E402

cams = {}
real_camera = L.camera


def recording_camera(sc, loc, target, lens=50, shift=(0, 0), focus=None, fstop=None, name='CAM'):
    cam = real_camera(sc, loc, target, lens=lens, shift=shift, focus=focus, fstop=fstop, name=name)
    cams[name] = (cam, Vector(target))
    return cam


L.camera = recording_camera
S.L.camera = recording_camera
L.render = lambda *a, **k: None
S.L.render = L.render

for name in ('hero', 'ring', 'final', 'views'):
    S.SHOTS[name]()


def gl(v):
    """Blender (x, y, z) → glTF (x, z, -y)."""
    return [round(v.x, 5), round(v.z, 5), round(-v.y, 5)]


ASPECT = {'hero_desk': 1.5, 'hero_portrait': 0.6, 'ring_desktop': 1.5, 'ring_portrait': 0.6,
          'final_desk': 1.5, 'final_portrait': 0.6}
out = {}
for name, (cam, target) in cams.items():
    m = cam.rotation_euler.to_matrix()  # matrix_world is stale until the scene evaluates
    out[name] = {
        'pos': gl(cam.location),
        'target': gl(target),
        'up': gl(m @ Vector((0, 1, 0))),
        'lens': round(cam.data.lens, 3),
        'shift': [round(cam.data.shift_x, 4), round(cam.data.shift_y, 4)],
        'aspect': ASPECT.get(name, 1.0),
    }

# each cup's outward axis (the Ring's plane normal), for the exploded view
sc = L.new_scene('axes', (100, 100))
p = L.product(sc)
P, C, n, v, w = S.ring_frame(p)
axisR = Vector(tuple(n))
axisL = Vector((-n[0], n[1], n[2]))
out_axes = {'R': gl(axisR), 'L': gl(axisL), 'centreR': gl(Vector(tuple(C))), 'centreL': gl(Vector((-C[0], C[1], C[2])))}

dst = L.REPO / 'src' / 'projects' / 'pulse' / 'stage-cams.ts'
dst.write_text(
    '// Generated by production/pipeline/export_cameras.py from the Blender shots: every camera in\n'
    '// glTF / three.js coordinates (Y up, metres), and each cup\'s outward axis. Do not edit by hand.\n'
    'export interface ShotCamera {\n  pos: number[]\n  target: number[]\n  up: number[]\n  lens: number\n'
    '  shift: number[]\n  aspect: number\n}\n'
    f'export const SHOT_CAMERAS: Record<string, ShotCamera> = {json.dumps(out, indent=2)}\n'
    f'export const CUP_AXES = {json.dumps(out_axes)}\n',
    encoding='utf-8',
)
print('PULSE_CAMS', dst, sorted(out))
