// Publishes the renders to the site: production/renders/*.png → public/projects/pulse/*.avif,
// frame sequences → MP4 loops, and the GLB. Run from production/pipeline: node publish.mjs [names…]
//
// Near-black gradients band once quantised to 8 bits, so every still is dithered from its 16-bit
// render with a fine film grain before encoding — the grain is part of the look, not a fix.
import sharp from 'sharp'
import ffmpeg from 'ffmpeg-static'
import { execFileSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const RENDERS = '../renders'
const FRAMES = process.env.PULSE_FRAMES || join(RENDERS, 'frames')
const OUT = '../../public/projects/pulse'
mkdirSync(OUT, { recursive: true })

const STILLS = [
  'hero-01', 'hero-01-m', 'ring-macro-01', 'ring-macro-01-m', 'mat-01', 'mat-02', 'mat-03',
  'phys-01', 'phys-02', 'phys-03', 'camp-space-01', 'camp-space-01-m', 'camp-arch-01', 'camp-arch-01-m',
  'camp-product-01', 'final-01', 'final-01-m',
]
const VIEWS = ['view-front', 'view-side', 'view-back', 'view-34']
const LOOPS = [
  ['hero', 'hero-01.mp4'],
  ['hero-m', 'hero-01-m.mp4'],
  ['phys1', 'phys-01.mp4'],
]

const only = process.argv.slice(2)
const wanted = (name) => !only.length || only.includes(name)
const kb = (f) => `${Math.round(statSync(f).size / 1024)} KB`

// a seeded normal distribution, so re-publishing gives identical files
let seed = 1
const rand = () => ((seed = (seed * 16807) % 2147483647) / 2147483647)
const gauss = () => Math.sqrt(-2 * Math.log(rand() + 1e-12)) * Math.cos(2 * Math.PI * rand())

async function still(name, { alpha = false, grain = 2, quality = 88 } = {}) {
  const src = join(RENDERS, `${name}.png`)
  if (!existsSync(src)) return console.log('missing', src)
  const pipe = alpha ? sharp(src).ensureAlpha() : sharp(src).removeAlpha()
  const { data: raw, info } = await pipe.toColourspace('rgb16').raw({ depth: 'ushort' }).toBuffer({ resolveWithObject: true })
  const { width, height, channels: ch } = info
  const src16 = new Uint16Array(raw.buffer, raw.byteOffset, raw.byteLength / 2)
  const out8 = Buffer.alloc(width * height * ch)
  for (let i = 0, p = 0; p < width * height; p++) {
    const n = gauss() * grain // luminance grain, the same on every channel of a pixel
    for (let c = 0; c < ch; c++, i++) {
      const v = src16[i] / 257
      out8[i] = c === 3 ? Math.round(v) : Math.max(0, Math.min(255, Math.round(v + n + (rand() - 0.5))))
    }
  }
  const dst = join(OUT, `${name}.avif`)
  await sharp(out8, { raw: { width, height, channels: ch } }).avif({ quality, effort: 6, chromaSubsampling: '4:4:4' }).toFile(dst)
  console.log('still', dst, `${width}×${height}`, kb(dst))
}

function loop(dir, file, crf = 23) {
  const frames = join(FRAMES, dir)
  if (!existsSync(join(frames, '0000.png'))) return console.log('missing frames', frames)
  const dst = join(OUT, file)
  execFileSync(ffmpeg, [
    '-y', '-loglevel', 'error', '-framerate', '24', '-i', join(frames, '%04d.png'),
    '-vf', 'noise=alls=3:allf=t,format=yuv420p', '-c:v', 'libx264', '-preset', 'slow', '-crf', String(crf),
    '-profile:v', 'high', '-movflags', '+faststart', '-an', dst,
  ])
  console.log('loop', dst, kb(dst))
}

const DENSE = { 'camp-product-01': 76, 'phys-02': 78 } // dust: fine detail everywhere, so a lower quality costs nothing visible
for (const name of STILLS) if (wanted(name)) await still(name, DENSE[name] ? { quality: DENSE[name] } : {})
for (const name of VIEWS) if (wanted(name)) await still(name, { alpha: true, grain: 0.8, quality: 64 })
for (const [dir, file] of LOOPS) if (wanted(dir)) loop(dir, file)
if (wanted('glb') && existsSync('../pulse-3d/pulse-01.glb')) {
  copyFileSync('../pulse-3d/pulse-01.glb', join(OUT, 'pulse-01.glb'))
  console.log('glb', join(OUT, 'pulse-01.glb'), kb(join(OUT, 'pulse-01.glb')))
}

// The Signature Ring's centreline as the ring-macro camera saw it (measured from the 3D master
// by pulse_shots.trace_ring), written as a module the case study imports
if (wanted('trace') && existsSync(join(RENDERS, 'ring-trace.json'))) {
  const t = JSON.parse(readFileSync(join(RENDERS, 'ring-trace.json'), 'utf8'))
  const frame = (f) => `{ size: [${f.size[0]}, ${f.size[1]}] as [number, number], d: '${f.d}' }`
  writeFileSync(
    '../../src/projects/pulse/ring-trace.ts',
    `// Generated by production/pipeline/publish.mjs from the ring-macro render: the Signature Ring's\n` +
      `// centreline as the camera saw it, in each frame's own pixels. Do not edit by hand.\n` +
      `export const RING_TRACE = {\n  desktop: ${frame(t.desktop)},\n  portrait: ${frame(t.portrait)},\n}\n`,
  )
  console.log('trace', 'src/projects/pulse/ring-trace.ts')
}

// the Draco decoder the viewer needs for the compressed GLB, from the site's own three.js
if (wanted('glb')) {
  const dir = '../../node_modules/three/examples/jsm/libs/draco/gltf'
  mkdirSync(join(OUT, 'draco'), { recursive: true })
  for (const f of ['draco_decoder.wasm', 'draco_wasm_wrapper.js', 'draco_decoder.js']) copyFileSync(join(dir, f), join(OUT, 'draco', f))
  console.log('draco', join(OUT, 'draco'))
}
